language: python

python:
    "3.6-dev"

before_install:
    "python3 setup.py install"

install:
    pip install -r requirements.txt

script: 
    pytest

deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "FILE TO UPLOAD"
  skip_cleanup: true
  on:
    tags: true
